# 1. Create a 3x3x3 array with random values 

In [ ]:

#`hint: np.random.random`
import numpy as np

Z = np.random.random((3,3,3))
print(Z)

[[[0.3600993  0.56232653 0.46827934]
  [0.53178824 0.88785678 0.43662903]
  [0.48488989 0.53305688 0.49929549]]

 [[0.33111438 0.24609699 0.37021414]
  [0.80310406 0.3335274  0.53716096]
  [0.86895857 0.85768863 0.29170979]]

 [[0.1315598  0.97594478 0.60314964]
  [0.29035313 0.22163402 0.19083284]
  [0.55806114 0.7956121  0.32239676]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [ ]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.27756774  0.72748002 -0.86930016 -1.47442475 -0.47166285]
 [-0.03783919 -0.75904244 -0.53361097  0.39653066  1.18964016]
 [-1.3850411   1.43028084 -0.85840215  0.43735974 -0.75580605]
 [ 0.43881117  0.39106811 -1.12001889 -0.74089861 -1.78325976]
 [ 1.54615561  1.61827629  1.59396818  0.06367867  0.67848973]]


# 5.  How to find common values between two arrays?

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[2 7 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2020-07-22
2020-07-23
2020-07-24


# 7. Consider two random array A and B, check if they are equal

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.76179618 0.76136066 0.57048147 0.06821329 0.         0.71281865
 0.34535246 0.119936   0.12519403 0.31697747]


# 9. How to print all the values of an array?

In [ ]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [ ]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y1 = X - X.mean(axis=1).reshape(-1, 1)

print(Y)
print(Y1)

[[ 0.03022044 -0.51373022 -0.03887334  0.21725562  0.22664352 -0.24188111
   0.42742935 -0.09805449  0.01198086 -0.02099062]
 [-0.2852209   0.41245135 -0.2548909  -0.11860637 -0.04121376  0.10999162
  -0.33015909  0.44909574 -0.19971704  0.25826936]
 [ 0.20377276  0.1609935  -0.30466712  0.38854966  0.07645236  0.43079717
  -0.21836698 -0.46710225 -0.07422605 -0.19620304]
 [-0.09089454 -0.45221862 -0.01204566  0.26944948  0.23214419  0.21974285
  -0.20101453  0.23316948 -0.39776523  0.19943259]
 [-0.23995449  0.16500733 -0.16381377  0.0221665   0.34981482 -0.3152606
   0.41731774 -0.13309451 -0.17144662  0.06926359]]
[[ 0.03022044 -0.51373022 -0.03887334  0.21725562  0.22664352 -0.24188111
   0.42742935 -0.09805449  0.01198086 -0.02099062]
 [-0.2852209   0.41245135 -0.2548909  -0.11860637 -0.04121376  0.10999162
  -0.33015909  0.44909574 -0.19971704  0.25826936]
 [ 0.20377276  0.1609935  -0.30466712  0.38854966  0.07645236  0.43079717
  -0.21836698 -0.46710225 -0.07422605 -0.19620304]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 2. 2. 4. 4. 3. 1. 4. 2. 4.]


In [ ]:
np.add.at(Z, I, 1)
print(Z)

[7. 3. 3. 7. 7. 5. 1. 7. 3. 7.]


# 12.How to get the diagonal of a dot product?

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.58178833 0.76658825 0.61477495 0.12653061 0.86772132]
 [0.46757268 0.38641674 0.80761341 0.25715911 0.45104287]
 [0.73865237 0.4749705  0.06653438 0.99364804 0.34618558]
 [0.68015717 0.59553642 0.01168946 0.06275222 0.9848539 ]
 [0.26216036 0.17066338 0.19331973 0.79120091 0.23940699]]
[[0.57201191 0.46620129 0.90364766 0.812761   0.93358363]
 [0.40040022 0.78733798 0.23231254 0.84865637 0.56652973]
 [0.92603188 0.11353386 0.68349069 0.93702432 0.89356843]
 [0.20652459 0.22272549 0.13153942 0.64420725 0.89934241]
 [0.87464973 0.89226641 0.92996362 0.70392899 0.55025684]]
diagonal of a dot product method 1 is.... [1.99411706 1.07364132 1.2759426  1.80285695 1.35747477]
diagonal of a dot product method 2 is.... [1.99411706 1.07364132 1.2759426  1.80285695 1.35747477]


# 13.How to find the most frequent value in an array?

In [ ]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[2 6 6 9 4 3 2 1 7 6 8 8 6 7 6 3 7 6 2 1 8 6 1 8 2 4 6 3 8 6 5 8 6 0 7 8 3
 4 4 1 7 9 9 1 0 0 7 0 5 7]
6


# 14.How to get the n largest values of an array

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])



[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
